#!/bin/bash
#SBATCH -J validation_big       # Job name
#SBATCH -o job.%j.out     # Name of stdout output file (%j expands to jobId)
#SBATCH --cpus-per-task=16               # Schedule number of cores
#SBATCH -t 4-10:00:00       # Run time (hh:mm:ss)
#SBATCH -p red      # Run on either the Red or Brown queue
#SBATCH --mem-per-cpu=10G
#SBATCH --ntasks=2

echo "Running on $(hostname):" # showing which node it is running on
module load Anaconda3
source /opt/itu/easybuild/software/Anaconda3/2021.11/bin/activate # path from ">>conda info | grep -i 'base environment'"+"/bin/activate" 
conda init bash # so that activate environment works 
conda activate cycregenv
python validation_big.py